services:
  - type: web
    name: telegram-attendance-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: TZ
        value: Asia/Phnom_Penh
      - key: DEFAULT_FINE_AMOUNT
        value: 20
      - key: ATTENDANCE_WINDOW_START
        value: 09:00
      - key: ATTENDANCE_WINDOW_END
        value: 10:00
      - key: REPORT_TIME
        value: 10:05

databases:
  - name: attendance-bot-db
    plan: free
    databaseName: attendance_bot
    user: postgres

